### ISSUE TITLE
invalid literal with _DISABLE_ERRORS_IF_LESS_THAN

### ISSUE THREAD

**Issue by omusavi** [nvuillam/mega-linter#359]
**Describe the bug**
Setting the config value for the *_DISABLE_ERRORS_IF_LESS_THAN throws an error: 
```
ValueError: invalid literal for int() with base 10: 'YAML_V8R_DISABLE_ERRORS_IF_LESS_THAN'
```

**To Reproduce**

1. Create a YAML file with a single schema error in it
2. Set `YAML_V8R_DISABLE_ERRORS_IF_LESS_THAN: 1` in `.mega-linter.yml`
3. Run `mega-linter-runner`

**Expected behavior**
Single error is ignored

**Actual Behavior**
Error: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
  File "/megalinter/MegaLinter.py", line 94, in __init__
    self.load_linters()
  File "/megalinter/MegaLinter.py", line 336, in load_linters
    all_linters = linter_factory.list_all_linters(linter_init_params)
  File "/megalinter/linter_factory.py", line 30, in list_all_linters
    descriptor_linters = build_descriptor_linters(
  File "/megalinter/linter_factory.py", line 92, in build_descriptor_linters
    linter_instance = linter_class(linter_init_params, instance_attributes)
  File "/megalinter/Linter.py", line 213, in __init__
    self.load_config_vars()
  File "/megalinter/Linter.py", line 387, in load_config_vars
    self.disable_errors_if_less_than = int(
ValueError: invalid literal for int() with base 10: 'YAML_V8R_DISABLE_ERRORS_IF_LESS_THAN'
```

**Screenshots**

**Additional context**
I tried this with other linters and ran into the same issue, so looks like a common problem because I believe this is a common property

**Comment by nvuillam** [comment]
Solved with 4.29.0 :) ( available in 30mn, the time the images ^^)
If you are in a hurry, you can use @insiders version :)

**Comment by omusavi** [comment]
Thanks for the quick fix!

**Comment by nvuillam** [comment]
You're welcome :)
