### ISSUE TITLE
Typescript error from Spectral in console

### ISSUE THREAD

**Issue by madsh** [nvuillam/mega-linter#375]
**Describe the bug**
Using the OpenAPI linter I get an error from inside spectral. It looks like a few letters missing in a typesript file. 'conte' could be 'content'...

**To Reproduce**
Validate a OpenAPI yaml file. 

**Expected behavior**
The internal error does not show up in the console. 

**Screenshots**

OpenAPI 3.x detected
TypeError: Unknown value type conte
    at JSONPath._trace (/home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:766:17)
    at /home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:745:23
    at /home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:909:9
    at Array.forEach (<anonymous>)
    at JSONPath._walk (/home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:908:24)
    at JSONPath._trace (/home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:743:12)
    at JSONPath._trace (/home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:698:19)
    at /home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:706:23
    at /home/circleci/.npm/_npx/10/lib/node_modules/@stoplight/spectral/node_modules/jsonpath-plus/dist/index-umd.js:909:9
    at Array.forEach (<anonymous>)

**Additional context**

**Comment by nvuillam** [comment]
@madsh > This is a bug for https://github.com/stoplightio/spectral :)
