### ISSUE TITLE
Contribution - build doc

### ISSUE THREAD

**Issue by llaville** [nvuillam/mega-linter#745]
While trying to run `build.sh --doc` with a fresh git version (latest commit is `396fc2ab14cb4586a89731342a40051605be06e8`), I get an error. 
Can you help me to understand whats happened ?

```
2021-09-17 17:58:30,983 [INFO] Fetching docker pull counters on flavors images
2021-09-17 17:58:31,879 [INFO] - docker pulls for all: 125312
Traceback (most recent call last):
  File "./.automation/build.py", line 2032, in <module>
    generate_all_flavors()
  File "./.automation/build.py", line 87, in generate_all_flavors
    update_docker_pulls_counter()
  File "./.automation/build.py", line 1274, in update_docker_pulls_counter
    flavor_stats = keep_one_stat_by_day(flavor_stats)
  File "./.automation/build.py", line 1298, in keep_one_stat_by_day
    count_date = datetime.fromisoformat(count_date_iso).date()
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by llaville** [comment]
Without `doc` option, all run fine, terminated with 

```
npx: installed 28 in 3.496s
No markdown table formatting has been applied.
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/llaville/devilbox_data/backups/github/my-mega-linter/site
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - descriptor-schema.md
              - descriptors/markdown_markdown_table_prettify.md
              - descriptors/salesforce_sfdx_scanner.md
WARNING  -  A relative path to './supported-linters/#languages' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to './supported-linters/#formats' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to './supported-linters/#tooling-formats' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to './supported-linters/#other' is included in the 'nav' configuration, which is not found in the documentation files
INFO     -  Documentation built in 12.25 seconds
```

**Comment by nvuillam** [comment]
What is your version of python ?

**Comment by nvuillam** [comment]
https://stackoverflow.com/a/60266709/7113625 :)

**Comment by llaville** [comment]
As I'm on Ubuntu 18.04, Python 3.6 was installed by default.
To keep my OS env BC, I've installed also python 3.7, following alternative https://www.itsupportwale.com/blog/how-to-upgrade-to-python-3-7-on-ubuntu-18-10/

And now `build.sh --doc` run fine !
Thanks to help me to point origin of issue 

BTW, I recommand you to add a caution about python3 min version required in page https://nvuillam.github.io/mega-linter/contributing/, to avoid future user to have the same issue.
