### ISSUE TITLE
[v4.46] Cannot override EDITORCONFIG_EDITORCONFIG_CHECKER cli_lint_mode with list_of_files

### ISSUE THREAD

**Issue by llaville** [nvuillam/mega-linter#831]
**Describe the bug**
EDITORCONFIG_CHECKER allows usage of multiple file and directory on same call, but current version 4.46.0 of Mega-Linter [do not accept](https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/Linter.py#L415-L421) to switch to `list_of_files` mode

**To Reproduce**
1. Have a repository (i.e: https://github.com/llaville/docker-php-toolbox)
2. Add at least a `.mega-linter.yml` config file with following contents: 
```
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
EXCLUDED_DIRECTORIES: [".git", "vendor"]
ENABLE:
    - EDITORCONFIG
EDITORCONFIG_EDITORCONFIG_CHECKER_CLI_LINT_MODE: list_of_files
```
3. See error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
  File "/megalinter/MegaLinter.py", line 96, in __init__
    self.load_linters()
  File "/megalinter/MegaLinter.py", line 344, in load_linters
    all_linters = linter_factory.list_all_linters(linter_init_params)
  File "/megalinter/linter_factory.py", line 30, in list_all_linters
    descriptor_linters = build_descriptor_linters(
  File "/megalinter/linter_factory.py", line 92, in build_descriptor_linters
    linter_instance = linter_class(linter_init_params, instance_attributes)
  File "/megalinter/Linter.py", line 223, in __init__
    self.load_config_vars()
  File "/megalinter/Linter.py", line 418, in load_config_vars
    raise KeyError(
KeyError: 'You can not override {self.name} cli_lint_mode with list_of_files, as it can process files only one by one. If you think it could be done, post an issue :)'
```

**Expected behavior**
editorconfig-checker should scan all files at once (for a better performance, compare to `file` mode)

Verified by native Docker image:
![ecc_listfiles_allowed](https://user-images.githubusercontent.com/364342/136689455-9f0c657f-55a8-4050-9791-404231c0ea67.png)

**Screenshots**
Perf comparaison (even with few files scanned)

* `project` mode
![ec_project_mode](https://user-images.githubusercontent.com/364342/136689358-52690a16-d183-4d77-af51-b4da8543f483.png)

* `list_of_files` mode
![ec_listfiles_mode](https://user-images.githubusercontent.com/364342/136689574-0b0fbf98-b9af-42d2-84c3-544f2b1ac943.png)

* `file` mode
![ec_file_mode](https://user-images.githubusercontent.com/364342/136689377-9ee48575-a2f2-475b-bd07-ddc02d3eff88.png)

PR will follows soon ... after actionlint patch ;-)

**Comment by llaville** [comment]
@nvuillam PR is ready to review / merge. Only a trivy timeout !
